export const SET_UNIVERSE_ID = 'SET_UNIVERSE_ID';
export const LOADING_UNIVERSE_INFO = 'LOADED_UNIVERSE_INFO';
export const LOADED_UNIVERSE_INFO = 'LOADED_UNIVERSE_INFO';


export const SET_CATEGORY_ID = 'SET_CATEGORY_ID';
export const LOADING_CATEGORY_INFO = 'LOADING_CATEGORY_INFO';
export const LOADED_CATEGORY_INFO = 'LOADED_CATEGORY_INFO';
