export const SET_UNIVERSE_ID = 'SET_UNIVERSE_ID';
export const LOADING_UNIVERSE_INFO = 'LOADED_UNIVERSE_INFO';
export const LOADED_UNIVERSE_INFO = 'LOADED_UNIVERSE_INFO';

export const SET_CATEGORY_ID = 'SET_CATEGORY_ID';
export const LOADING_CATEGORY_INFO = 'LOADING_CATEGORY_INFO';
export const LOADED_CATEGORY_INFO = 'LOADED_CATEGORY_INFO';

export const SET_MARKET_ID = 'SET_MARKET_ID';
export const LOADING_MARKET_INFO = 'LOADING_MARKET_INFO';
export const LOADED_MARKET_INFO = 'LOADED_MARKET_INFO';

export const SET_PRODUCT_ID = 'SET_PRODUCT_ID';
export const LOADING_PRODUCT_INFO = 'LOADING_PRODUCT_INFO';
export const LOADED_PRODUCT_INFO = 'LOADED_PRODUCT_INFO';
